sudo: required

env:
  global:
    - IMAGE_NAME=darkowlzz/image-push-test

#before_script:
  #- sudo apt -y update
  #- sudo apt -y install linux-image-extra-$(uname -r)
  #- sudo mount --make-rshared /sys
  #- docker run --name enable_lio --privileged --rm --cap-add=SYS_ADMIN -v /lib/modules:/lib/modules -v /sys:/sys:rshared storageos/init:0.1

script:
  - docker build -t "$IMAGE_NAME" .
  - echo "TRAVIS TAG ${TRAVIS_TAG}"
  - echo "TRAVIS BRANCH ${TRAVIS_BRANCH}"
  - echo "DONE"
  - curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.3.0/operator-sdk-v0.3.0-x86_64-linux-gnu && chmod +x operator-sdk && mv operator-sdk /usr/local/bin/
  - ls /usr/local/bin/

after_script:
  - docker images

before_deploy:
  - echo "DEPLOYING..."
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true

